### ISSUE TITLE
[CLIENT][FEAT] 메인페이지 라우팅

### ISSUE THREAD

**Issue by weed7968** [codestates-seb/seb44_main_021#31]
**요구사항 ID**
PAG-002

**요구사항**
기사 및 소개글 클릭 시 상세 페이지로 이동해야함

**상세 요구사항**

**TODO**
- [ ] 비로그인시 프로필 클릭하면 로그인 페이지로 이동하는가?
- [ ] 햄버거 카테고리에서 각 버튼 클릭시 알맞은 페이지로 이동하는가?
- [ ] 기사 및 소개글 클릭 시 상세 페이지로 이동하는가?
