### ISSUE TITLE
[CLIENT][FEAT] 펀딩 상세페이지 기능

### ISSUE THREAD

**Issue by weed7968** [codestates-seb/seb44_main_021#52]
**요구사항 ID**
UPC-002

**요구사항**
펀딩 상세페이지 기능

**상세 요구사항**
이미지 슬라이더, 모달, edit버튼 활성 구현

**TODO**
- [ ] 이미지 안의 화살표 클릭시 넘어가는가? 
- [ ] 마지막 이미지에서 첫번째 이미지로 돌아오는가?
- [ ] 펀딩하기 버튼 클릭시 모달 창을 잘 띄우는가?
- [ ] 업사이클러로 로그인시 edit 버튼이 활성화 되는가?
