### ISSUE TITLE
[CLIENT][FEAT] 펀딩 상세페이지 모달

### ISSUE THREAD

**Issue by weed7968** [codestates-seb/seb44_main_021#53]
**요구사항 ID**
UPC-002

**요구사항**
펀딩 상세페이지 모달창 구현

**상세 요구사항**
모달창 CSS, 데이터, 라우팅 구현

**TODO**
- [ ] 해당 모달에 필요한 정보를 잘 불러오는가?(사용자명, 펀딩명, 자재)
- [ ] 해당 모달에 필요한 정보를 잘 불러오는가?(사용자명, 펀딩명, 자재)
- [ ] 다른 펀딩 더 보러가기 클릭시 펀딩 리스트 페이지로 이동하는가?
- [ ] 펀딩하기 클릭시 모달 화면이 전화되는가?
