### ISSUE TITLE
[CLIENT][FEAT] 스토어 상세페이지 기능

### ISSUE THREAD

**Issue by weed7968** [codestates-seb/seb44_main_021#60]
**요구사항 ID**
ITE-001

**요구사항**
스토어 상세페이지 기능

**상세 요구사항**
스토어 상세페이지 기능 구현하기

**TODO**
- [ ] 수량 선택시 계산되어 총합 금액에 나오는가?
- [ ] 구매하기 버튼 클릭시 모달 창을 잘 띄우는가?
- [ ] 업사이클러로 로그인시 edit 버튼이 활성화 되는가?
