### ISSUE TITLE
[CLIENT] 스토어 상세페이지 모달

### ISSUE THREAD

**Issue by weed7968** [codestates-seb/seb44_main_021#61]
**요구사항 ID**
ITE-001

**요구사항**
스토어 상세페이지 모달 구현

**상세 요구사항**
데이터 불러오기, 라우팅 연결

**TODO**
- [ ] 해당 모달에 필요한 정보를 잘 불러오는가?(사용자명, 제품명, 수량, 결제금액)
- [ ] 구매내역 보러가기 버튼 클릭시 마이페이지로 이동하는가?
- [ ] 스토어 제품 더 보러가기 버튼 클릭시 스토어 list로 이동하는가?
